field_labels = {
            "ID_street": "Улицы",
            "house": "Дом",
            "building_body": "Корпус",
            "latitude": "Широта",
            "longitude": "Долгота",
            "year_construction": "Год постройки",
            "number_floors": "Количество этажей",
            "number_entrances": "Количество подъездов",
            "number_buildings": "Количество строений",
            "number_living_quarters": "Количество жилых помещений",
            "title": "Название",
            "ID_type_construction": "Тип конструкции",
            "ID_basic_project": "Типовой проект",
            "ID_appointment": "Назначение",
            "seismic_resistance_min": "Расчетная сейсмостойкость min",
            "seismic_resistance_max": "Расчетная сейсмостойкость max",
            "zone_SMZ_min": "Зона по карте СМР min",
            "zone_SMZ_max": "Зона по карте СМР max",
            "priming": "Грунт",
            "ID_load_bearing_walls": "Несущие стены",
            "basement_area": "Площадь подвала",
            "ID_building_roof": "Крыша",
            "ID_building_floor": "Перекрытия",
            "ID_facade": "Фасад",
            "ID_foundation": "Фундамент",
            "azimuth": "Расположение по сторонам света",
            "cadastral_number": "Кадастровый номер",
            "cadastral_cost": "Кадастровая стоимость",
            "year_overhaul": "Год капремонта",
            "accident_rate": "Аварийность",
            "ID_management_company": "Управляющая компания",
            "Land_area": "Площадь земельного участка общего имущества м2",
            "notes": "Примечания",
            "author": "Источник данных"
        }